# Generated by Django 5.1.7 on 2025-03-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toiletbutton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('sound_name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='sound_images')),
                ('sound', models.FileField(upload_to='sound_files')),
            ],
        ),
    ]
